var postTitle=[],postUrl=[],postPublished=[],postDate=[],postLabels=[],postRecent=[],sortBy="titleasc",tocLoaded=!1,numChars=250,postFilter="",numberfeed=0;
function bloggersitemap(c){if("entry"in c.feed){var d=c.feed.entry.length;numberfeed=d;for(var b=ii=0;b<d;b++){for(var a=c.feed.entry[b],e=a.title.$t,f=a.published.$t.substring(0,10),g,h=0;h<a.link.length;h++)if("alternate"==a.link[h].rel){g=a.link[h].href;break}for(var l="",h=0;h<a.link.length;h++)if("enclosure"==a.link[h].rel){l=a.link[h].href;break}var k;if("category"in a)for(h=0;h<a.category.length;h++){k=a.category[h].term;var m=k.lastIndexOf(";");-1!=m&&(k=k.substring(0,m));postLabels[ii]=k;
postTitle[ii]=e;postDate[ii]=f;postUrl[ii]=g;postPublished[ii]=l;postRecent[ii]=10>b?!0:!1;ii+=1}}}sortBy="titleasc";sortPosts(sortBy);sortlabel();tocLoaded=!0;displayToc2()}function filterPosts(c){scroll(0,0);postFilter=c;displayToc(postFilter)}function allPosts(){sortlabel();postFilter="";displayToc(postFilter)}
function sortPosts(c){function d(a,b){var c=postTitle[a];postTitle[a]=postTitle[b];postTitle[b]=c;c=postDate[a];postDate[a]=postDate[b];postDate[b]=c;c=postUrl[a];postUrl[a]=postUrl[b];postUrl[b]=c;c=postLabels[a];postLabels[a]=postLabels[b];postLabels[b]=c;c=postPublished[a];postPublished[a]=postPublished[b];postPublished[b]=c;c=postRecent[a];postRecent[a]=postRecent[b];postRecent[b]=c}for(var b=0;b<postTitle.length-1;b++)for(var a=b+1;a<postTitle.length;a++)"titleasc"==c&&postTitle[b]>postTitle[a]&&
d(b,a),"titledesc"==c&&postTitle[b]<postTitle[a]&&d(b,a),"dateoldest"==c&&postDate[b]>postDate[a]&&d(b,a),"datenewest"==c&&postDate[b]<postDate[a]&&d(b,a),"orderlabel"==c&&postLabels[b]>postLabels[a]&&d(b,a)}function sortlabel(){sortBy="orderlabel";sortPosts(sortBy);for(var c=0,d=0;d<postTitle.length;){temp1=postLabels[d];firsti=c;do c+=1;while(postLabels[c]==temp1);d=c;sortPosts2(firsti,c);if(d>postTitle.length)break}}
function sortPosts2(c,d){for(var b=c;b<d-1;b++)for(var a=b+1;a<d;a++)if(postTitle[b]>postTitle[a]){var e=b,f=a,g=postTitle[e];postTitle[e]=postTitle[f];postTitle[f]=g;g=postDate[e];postDate[e]=postDate[f];postDate[f]=g;g=postUrl[e];postUrl[e]=postUrl[f];postUrl[f]=g;g=postLabels[e];postLabels[e]=postLabels[f];postLabels[f]=g;g=postPublished[e];postPublished[e]=postPublished[f];postPublished[f]=g;g=postRecent[e];postRecent[e]=postRecent[f];postRecent[f]=g}}
function displayToc(c){var d=0,b;b="Click to sort by title";var a="Click to sort by date",e="";"titleasc"==sortBy&&(b+=" (descending)",a+=" (newest first)");"titledesc"==sortBy&&(b+=" (ascending)",a+=" (newest first)");"dateoldest"==sortBy&&(b+=" (ascending)",a+=" (newest first)");"datenewest"==sortBy&&(b+=" (ascending)",a+=" (oldest first)");""!=postFilter&&(e="Click to view all");b='<table><tr><td class="header1">'+('<a href="javascript:toggleTitleSort();" title="'+b+'">Post Title</a>')+'</td><td class="header2">';
b+='<a href="javascript:toggleDateSort();" title="'+a+'">Date</a>';b+="</td>";b+='<td class="header3">';b+='<a href="javascript:allPosts();" title="'+e+'">Category</a>';b+="</td>";b+='<td class="header4">';b+="Read all";b+="</td>";b+="</tr>";for(a=0;a<postTitle.length;a++)""==c?(b+='<tr><td class="entry1"><a href="'+postUrl[a]+'">'+postTitle[a]+'</a></td><td class="entry2">'+postDate[a]+'</td><td class="entry3">'+postLabels[a]+'</td><td class="entry4"><a href="'+postPublished[a]+'">Read</a></td></tr>',
d++):(z=postLabels[a].lastIndexOf(c),-1!=z&&(b+='<tr><td class="entry1"><a href="'+postUrl[a]+'">'+postTitle[a]+'</a></td><td class="entry2">'+postDate[a]+'</td><td class="entry3">'+postLabels[a]+'</td><td class="entry4"><a href="'+postPublished[a]+'">Read</a></td></tr>',d++));b+="</table>";c=d==postTitle.length?'<span class="toc-note">Show All '+postTitle.length+" Posts<br/></span>":'<span class="toc-note">Show '+d+" posts by category '"+(postFilter+"' the "+postTitle.length+" Total Posts<br/></span>");
document.getElementById("toc").innerHTML=c+b}
function displayToc2(){for(var c=0,d=0;d<postTitle.length;){temp1=postLabels[d];document.write("<p/>");document.write('<p class="labels"><a href="/search/label/'+temp1+'">'+temp1+"</a></p><ol>");firsti=c;do document.write("<li>"),document.write('<a class="post-titles" href="'+postUrl[c]+'">'+postTitle[c]+"</a>"),1==postRecent[c]&&document.write(' - <strong><span style="color: rgb(255, 0, 0);">New!</span></strong>'),document.write("</li>"),c+=1;while(postLabels[c]==temp1);d=c;document.write("</ol>");
sortPosts2(firsti,c);if(d>postTitle.length)break}}function toggleTitleSort(){sortBy="titleasc"==sortBy?"titledesc":"titleasc";sortPosts(sortBy);displayToc(postFilter)}function toggleDateSort(){sortBy="datenewest"==sortBy?"dateoldest":"datenewest";sortPosts(sortBy);displayToc(postFilter)}function showToc(){tocLoaded?(displayToc(postFilter),document.getElementById("toclink")):alert("Just wait... TOC is loading")}
function hideToc(){document.getElementById("toc").innerHTML="";document.getElementById("toclink").innerHTML='<a href="#" onclick="scroll(0,0); showToc(); Effect.toggle(\'toc-result\',\'blind\');">?? Display Table of Contents</a> <img src="http://1.bp.blogspot.com/-_VZwBpHw_SI/UrXvLbFxacI/AAAAAAAAFiQ/ZGqWZUZesCI/s1600/new_icon.gif"/>'}
function looptemp2(){for(var c=0;c<numberfeed;c++)document.write("<br>"),document.write('Post Link : <a href="'+postUrl[c]+'">'+postTitle[c]+"</a><br>"),document.write('Read all : <a href="'+postPublished[c]+'">'+postTitle[c]+"</a><br>"),document.write("<br>")};